[build]
  command = "yarn build"
  publish = "public/"
  functions = "functions"  
  environment = { APP_ENV = "development" }

[context.production]
  environment = { APP_ENV = "production" }

[[redirects]]
  from = "https://labase-paris.netlify.com"
  to = "https://labase.paris"
  status = 301

[[redirects]]
  from = "https://labase-paris.netlify.com/*"
  to = "https://labase.paris/:splat"
  status = 301
