[build]
  publish = "src"

[[redirects]]
  from = "https://labase-paris.netlify.com"
  to = "https://labase-paris.paris"
  status = 301

[[redirects]]
  from = "https://labase-paris.netlify.com/*"
  to = "https://labase-paris.paris/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
